/**
 * -----------------------------------------------------------------------------
 * This file is auto-generated via scripts/generate-design-tokens.mjs.
 * Do not edit this file directly.
 * -----------------------------------------------------------------------------
 */

export const backgroundColorTokenOptions = [

] as const;

export const borderColorTokenOptions = [

] as const;

export const textColorTokenOptions = [

] as const;

export const spacingTokenOptions = [

] as const;

export const radiusTokenOptions = [

] as const;

export const borderWidthTokenOptions = [

] as const;

export const shadowTokenOptions = [

] as const;

export const storybookTokenOptionMap = {
  backgroundColor: backgroundColorTokenOptions,
  borderColor: borderColorTokenOptions,
  textColor: textColorTokenOptions,
  spacing: spacingTokenOptions,
  radius: radiusTokenOptions,
  borderWidth: borderWidthTokenOptions,
  shadow: shadowTokenOptions,
} as const;
