/**
 * -----------------------------------------------------------------------------
 * This file is auto-generated via scripts/generate-design-tokens.mjs.
 * Do not edit this file directly.
 * -----------------------------------------------------------------------------
 */

export const designTokenManifest = {
  "themes": [
    {
      "name": "Engage",
      "id": "internals-engage",
      "group": "Internals",
      "cssPath": "./engage.css",
      "selectedTokenSets": {
        "Internals/Engage": "enabled"
      },
      "activeTokenSets": [
        "Externals/Default",
        "Internals/Engage"
      ],
      "tokenSetCombination": {
        "external": [
          "Externals/Default"
        ],
        "internal": "Internals/Engage"
      }
    },
    {
      "name": "Legacy",
      "id": "cbb4ab9822ee0cabac71a6b5e23748f1e9d4e1ff",
      "group": "Internals",
      "cssPath": "./legacy.css",
      "selectedTokenSets": {
        "Internals/Legacy": "enabled"
      },
      "activeTokenSets": [
        "Externals/Default",
        "Internals/Legacy"
      ],
      "tokenSetCombination": {
        "external": [
          "Externals/Default"
        ],
        "internal": "Internals/Legacy"
      }
    }
  ],
  "metadata": {
    "tokenSetOrder": [
      "Internals/Engage",
      "Internals/Legacy",
      "Externals/Default"
    ]
  }
} as const;

export type DesignTokenTheme = typeof designTokenManifest.themes[number];
export type DesignTokenThemeName = DesignTokenTheme['name'];
